project:
  type: website

website:
  title: "Sydney Tomsick"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto