---
title: "A Clinical Study: The Effect of Caffeine and Exercise on Attention"
link-external-icon: true
link-external-newwindow: true
date: "September 2024"
---

In this clinical study, [*The Effect of Caffeine and Exercise on Attention*](Stats101B_Final_Project.pdf){style="color: blue;"}, I investigated whether caffeine intake and running distance significantly impact attention span using a 2-way factorial design with interactions. Both factors had three levels—caffeine (250mL green tea, 250mL coffee, 500mL coffee) and exercise (100m, 1km, 5km)—creating nine experimental groups. The study was conducted using *The Island*, an online simulation platform that allowed me to administer treatments and measure attention in simulated individuals. ANOVA and Tukey’s post-hoc tests revealed no statistically significant effect from caffeine, exercise, or their interaction on attention span, suggesting these variables do not meaningfully impact attentional performance in the context of this simulation.
