---
title: "Exploring Female Representation in MoMA"
date: "December 2024"
---

My team and I created a [website](https://exhibitexplorers.humspace.ucla.edu/) discussing the lack of female representation in art museums. We used the Artworks.csv dataset from this [GitHub repository](https://github.com/MuseumofModernArt/collection) created by the Museum of Modern Art (MoMA). The dataset includes the title of every art piece acquired by the MoMA museum in New York since its opening, demographic information about the artist, the date the art piece was acquired, whether the art piece is currently on view, and many more variables. We used this data to make visualizations showing how female artist representation has changed in MoMA over time both in the US and globally. Using our research, we discussed potential connections between changes in gender representation in MoMA and feminist movements taking place at the same time.

### Our Research Questions

1.  How did waves of feminism and American social movements of the mid-1900s affect the representation of American female artists in the MoMA collection? 

2.  Beyond the U.S., how did global feminist movements relate to the ethnic diversity of female artists in the MoMA collection?

### My Role

My main responsibility for this project was web design through WordPress. I also helped clean the data and create data visualizations.
