---
title: "Kaggle Competition: Predicting Obesity Status"
link-external-icon: true
link-external-newwindow: true
date: "December 2024"
---

### About

My team and I were provided with a training and testing dataset containing 29 predictors of obesity status capturing aspects such as dietary habits, physical activity, water consumption, and family medical history. The outcome variable "obesity status" classified individuals as either "Obese" or "Not Obese". We were tasked with predicting obesity status for the testing dataset and determining the most influential predictors. Here is my written [**Report**](Stats101C_Final_Paper.pdf){style="color: blue;"}**.**

### Methods

First, we imputed the data using random forests to fill in missing values. Then, we tried multiple models to predict obesity status such as logistic regression, decision trees, and random forests. Our random forests model with 500 trees performed best, with a testing prediction accuracy of 99.943%.

We then found the most influential predictors using correlation analysis (point-biserial and Cramer's V correlation) and variable importance from the random forests model.

#### 
